#version: "3.7"
#services:
  #anyApp:
    #image: ${DOCKER_REPO:-kontinu}/${PROJECT_LANG:-python}-expert:v1.0
    #build:
      #context: src/${PROJECT_LANG:-python}
      #context: ${PROJECT_LANG:-python}
    #ports:
      #- ${EXPOSE_PORT:-8080}:8080

version: "3.7"
services:
  python:
    image: ${DOCKER_REPO:-kontinu}/python-expert:v1.0
    build:
      context: src/python
    ports:
      - 8080:8080
  nodejs:
    image: ${DOCKER_REPO:-kontinu}/nodejs-expert:v1.0
    build:
      context: src/nodejs
    ports:
      - 8081:8080
  go:
    image: ${DOCKER_REPO:-kontinu}/go-expert:v1.0
    build:
      context: src/go
    ports:
      - 8082:8080 